import assert from 'node:assert/strict';
import fs from 'node:fs';
import { makeRecord, applyRecord, exportItem, validateRecord } from '../corrections.mjs';
const sha='a'.repeat(64);
const raw={filename:'same.m4v',sha256:sha,tags:[{tag:'solo',confidence:0.9,supportingFrames:4},{tag:'glasses',confidence:0.7,supportingFrames:2}],uncertain:['tattoos'],sampledFrames:4,threshold:0.5,model:'JoyTag-INT8',createdAt:'2026-10-03T12:00:00Z'};
const entry={file:{name:'same.m4v'},result:raw,selected:new Map([['solo',true],['glasses',false],['tattoos',true]]),reviewed:true};
const tags=fs.readFileSync('tags.txt','utf8').split(/\r?\n/).filter(Boolean);
const stored=validateRecord(makeRecord(entry),tags);
const restored=applyRecord({file:{name:'renamed.m4v'}},stored);
assert.deepEqual([...restored.selected],[['solo',true],['glasses',false],['tattoos',true]]);
assert.equal(restored.reviewed,true);
const exp=exportItem(restored);
assert.deepEqual(exp.addedTags,['tattoos']);assert.deepEqual(exp.removedTags,['glasses']);
assert.equal(exp.originalSuggestions[0].confidence,0.9);assert.equal(exp.threshold,0.5);
assert.equal(exp.filename,'renamed.m4v');assert.equal(exp.sha256,sha);
const legacy=applyRecord({file:{name:'old.m4v'}},{...stored,originalSuggestionsKnown:false,result:{...raw,tags:[]}});
assert.equal(exportItem(legacy).originalSuggestions,null);assert.equal(exportItem(legacy).addedTags,null);
assert.throws(()=>validateRecord({...stored,tags:['made up tag']},tags));
assert.throws(()=>validateRecord({...stored,result:{...stored.result,sha256:'b'.repeat(64)}},tags));
assert.throws(()=>validateRecord({...stored,result:{...stored.result,tags:[{tag:'solo',confidence:NaN}]}},tags));
console.log('Correction persistence/export semantics passed.');
